// Generated by CoffeeScript 1.9.1
var app, compression, express, jsonstore, oneDay, path, port, ql;

express = require('express');

compression = require('compression');

path = require('path');

ql = require('odoql/ql');

jsonstore = require('odoql-json/store');

app = express();

app.use(compression());

oneDay = 1000 * 60 * 60 * 24;

app.use(express["static"](__dirname, {
  maxAge: oneDay
}));

app.get('/*', function(req, res) {
  console.log(req.url);
  return res.sendFile(path.join(__dirname, 'index.html'));
});

port = 8085;

app.listen(port);

console.log("Wedding is listening on port " + port + "...");
