// Generated by CoffeeScript 1.9.2
var CSON, contents, file, files, fs, going, hasmodifier, i, id, j, k, keys, len, len1, len2, output, path, ref, ref1;

fs = require('fs');

path = require('path');

CSON = require('cson');

files = fs.readdirSync('./data');

for (i = 0, len = files.length; i < len; i++) {
  file = files[i];
  if (path.extname(file) !== '.cson') {
    continue;
  }
  contents = CSON.load("./data/" + file);
  hasmodifier = false;
  keys = Object.keys(contents);
  if (keys[1] === 'comments') {
    continue;
  }
//  console.log(contents.to + ' ' + file);
//  continue;
  going = false;
  ref = ['prewedding', 'ceremony', 'reception', 'breakfast'];
  for (j = 0, len1 = ref.length; j < len1; j++) {
    id = ref[j];
    if (!contents[id]) {
      continue;
    }
    going = going || contents[id].going;
  }
  if (!going) {
    continue;
  }
  output = contents.to + ":";
  ref1 = ['prewedding', 'ceremony', 'reception', 'breakfast'];
  for (k = 0, len2 = ref1.length; k < len2; k++) {
    id = ref1[k];
    if (!contents[id]) {
      continue;
    }
    if (!contents[id].going) {
      continue;
    }
    output += " " + id;
  }
  console.log(output);
}
