// Generated by CoffeeScript 1.9.2
var CSON, a, attending, contents, eventids, file, files, fs, going, hasmodifier, i, id, j, k, keys, l, len, len1, len2, len3, len4, len5, len6, m, n, notresponded, o, output, path, people, person, ref;

fs = require('fs');

path = require('path');

CSON = require('cson');

eventids = ['prewedding', 'ceremony', 'reception', 'breakfast'];

attending = {};

for (i = 0, len = eventids.length; i < len; i++) {
  id = eventids[i];
  attending[id] = [];
}

notresponded = [];

files = fs.readdirSync('./data');

for (j = 0, len1 = files.length; j < len1; j++) {
  file = files[j];
  if (path.extname(file) !== '.cson') {
    continue;
  }
  contents = CSON.load("./data/" + file);
  hasmodifier = false;
  keys = Object.keys(contents);
  if (keys[1] === 'comments') {
    notresponded.push(contents.to);
  }
  going = false;
  for (k = 0, len2 = eventids.length; k < len2; k++) {
    id = eventids[k];
    if (!contents[id]) {
      continue;
    }
    going = going || contents[id].going;
    ref = contents[id].attending;
    for (l = 0, len3 = ref.length; l < len3; l++) {
      a = ref[l];
      if (a === '') {
        continue;
      }
      attending[id].push(a);
    }
  }
  if (!going) {
    continue;
  }
  output = contents.to + ":";
  for (m = 0, len4 = eventids.length; m < len4; m++) {
    id = eventids[m];
    if (!contents[id]) {
      continue;
    }
    if (!contents[id].going) {
      continue;
    }
    output += " " + id;
  }
  console.log(output);
}

console.log();

console.log('Not responded:');

for (n = 0, len5 = notresponded.length; n < len5; n++) {
  person = notresponded[n];
  console.log("  " + person);
}

console.log();

for (id in attending) {
  people = attending[id];
  console.log(id + " (" + people.length + "):");
  for (o = 0, len6 = people.length; o < len6; o++) {
    person = people[o];
    console.log("  " + person);
  }
  console.log();
}
