// Generated by CoffeeScript 1.9.2
var hub, page, scene;

hub = require('odo-hub');

window.hub = hub;

page = require('page');

scene = require('./scene');

require('./intent');

page();

window.__loadinghandle.fin();
