// Generated by CoffeeScript 1.9.1
var get, jsonstore, localstore, stores;

jsonstore = require('odoql-json/store');

localstore = require('odoql-localstorage/store');

get = function(url, cb) {
  var http;
  http = new XMLHttpRequest();
  http.onreadystatechange = function() {
    if (http.readyState !== XMLHttpRequest.DONE) {
      return;
    }
    if (http.status === 200) {
      return cb(null, JSON.parse(http.responseText));
    }
    return cb({
      status: http.status,
      message: http.responseText
    });
  };
  http.open('GET', url, true);
  return http.send();
};

stores = {
  localstorage: localstore,
  __dynamic: function(query, cb) {
    query = encodeURIComponent(JSON.stringify(query));
    return get("/query?q=" + query, cb);
  }
};

module.exports = stores;
