// Generated by CoffeeScript 1.8.0
var data, hub;

hub = require('../lib/hub');

data = {
  to: 'Mr MacGoo and Partner',
  names: ['Mr MacGoo', '', '', '', '']
};

hub.every('update name {index} to {name}', function(p) {
  return console.log(p);
});

module.exports = data;
