// Generated by CoffeeScript 1.9.1
var component, dom, inject, ql, ref, svg, widget;

ref = require('odojs'), component = ref.component, dom = ref.dom, widget = ref.widget, svg = ref.svg;

inject = require('injectinto');

ql = require('odoql/ql');

inject.bind('page:default', component({
  render: function(state, params) {
    var titileattr;
    titileattr = {
      attributes: {
        "class": 'title'
      },
      style: {
        width: '100%'
      }
    };
    return dom('div', {
      attributes: {
        "class": 'wrapper'
      }
    }, [
      dom('h1', 'Joe Bloggs'), svg('svg', titileattr, [
        svg('use', {
          'xlink:href': "/dist/wedding-1.0.0.min.svg#title"
        })
      ])
    ]);
  }
}));
