// Generated by CoffeeScript 1.9.1
var component, dom, inject, ql, ref, widget;

ref = require('odojs'), component = ref.component, dom = ref.dom, widget = ref.widget;

inject = require('injectinto');

ql = require('odoql/ql');

inject.bind('page:default', component({
  render: function(state, params) {
    return dom('div', {
      attributes: {
        "class": 'wrapper grid'
      }
    }, ['HELLO THERE']);
  }
}));
