// Generated by CoffeeScript 1.9.2
var Emblem, component, inject, pjson, ref, svg;

ref = require('odojs'), svg = ref.svg, component = ref.component;

inject = require('injectinto');

require('svg4everybody');

pjson = require('../package.json');

Emblem = component({
  render: function() {
    return svg('svg', {
      attributes: {
        role: 'img',
        "class": 'emblem'
      }
    }, [
      svg('use', {
        'xlink:href': "/dist/" + pjson.name + "-" + pjson.version + ".min.svg#emblem"
      })
    ]);
  }
});

inject.bind('emblem', Emblem);

module.exports = Emblem;
