// Generated by CoffeeScript 1.9.2
var component, dom, inject, pjson, ref, svg;

ref = require('odojs'), component = ref.component, dom = ref.dom, svg = ref.svg;

inject = require('injectinto');

pjson = require('../package.json');

inject.bind('page:front', component({
  render: function(state, params) {
    var titileattr;
    titileattr = {
      attributes: {
        "class": 'title'
      },
      style: {
        width: '100%'
      }
    };
    return dom('div', {
      attributes: {
        "class": 'wrapper error grid grid--center'
      }
    }, [
      dom('div', [
        dom('div', {
          attributes: {
            "class": 'logo'
          }
        }, [
          svg('svg', titileattr, [
            svg('use', {
              'xlink:href': "/dist/" + pjson.name + "-" + pjson.version + ".min.svg#emblem"
            })
          ])
        ]), dom('div', [dom('h1', 'Thomas Coats and Harvinder Kaur'), dom('p', "You will need an invite code to RSVP")])
      ])
    ]);
  }
}));
