// Generated by CoffeeScript 1.9.2
var Gift, component, inject, ref, svg;

ref = require('odojs'), svg = ref.svg, component = ref.component;

inject = require('injectinto');

require('svg4everybody');

Gift = component({
  render: function() {
    return svg('svg', {
      attributes: {
        role: 'img',
        "class": 'gift'
      }
    }, [
      svg('use', {
        'xlink:href': "/dist/wedding-1.0.0.min.svg#gift"
      })
    ]);
  }
});

inject.bind('gift', Gift);

module.exports = Gift;
