// Generated by CoffeeScript 1.9.2
var Gift, component, inject, pjson, ref, svg;

ref = require('odojs'), svg = ref.svg, component = ref.component;

inject = require('injectinto');

require('svg4everybody');

pjson = require('../package.json');

Gift = component({
  render: function() {
    return svg('svg', {
      attributes: {
        role: 'img',
        "class": 'gift'
      }
    }, [
      svg('use', {
        'xlink:href': "/dist/" + pjson.name + "-" + pjson.version + ".min.svg#gift"
      })
    ]);
  }
});

inject.bind('gift', Gift);

module.exports = Gift;
