// Generated by CoffeeScript 1.8.0
var L, component, dom, _ref;

_ref = require('../lib/deku.min'), component = _ref.component, dom = _ref.dom;

L = require('../lib/leaflet-src.js');

module.exports = component({
  afterMount: function(el, props, state) {
    var invalidateSize, map, tiles;
    map = L.map(el).setView([51.505, -0.09], 8);
    tiles = L.tileLayer('http://otile{s}.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.jpg', {
      maxZoom: 10,
      attribution: '',
      subdomains: '1234'
    });
    tiles.addTo(map);
    invalidateSize = function() {
      return map.invalidateSize();
    };
    return this.setState({
      map: map,
      tiles: tiles
    }, invalidateSize);
  },
  beforeUnmount: function(el, props, state) {
    return state.map.remove();
  },
  render: function(props, state) {
    return dom('div', {
      id: 'map'
    });
  }
});
