// Generated by CoffeeScript 1.8.0
var calc, cycle, divisions, height, padding, path, pos, state, width;

cycle = function(cb) {
  var handle, prev, step;
  prev = null;
  handle = null;
  step = function(t) {
    var dt;
    if (prev === null) {
      prev = t;
      return handle = window.requestAnimationFrame(step);
    }
    dt = t - prev;
    prev = t;
    cb(dt);
    return handle = window.requestAnimationFrame(step);
  };
  handle = window.requestAnimationFrame(step);
  return {
    fin: function() {
      window.cancelAnimationFrame(handle);
      window.__loadinghandle = null;
      return document.querySelector('.loading').remove();
    }
  };
};

width = 150;

height = 50;

divisions = 15;

padding = 3;

pos = function(offset, index) {
  return "" + (padding + index * (width - padding * 2) / divisions) + " " + (height / 2 + (height / 2 - padding) * Math.sin(offset + 10 * index / divisions / Math.PI));
};

calc = function(offset) {
  var d, index, _i;
  d = "M" + (pos(offset, 0));
  for (index = _i = 1; 1 <= divisions ? _i <= divisions : _i >= divisions; index = 1 <= divisions ? ++_i : --_i) {
    d += "L" + (pos(offset, index));
  }
  return d;
};

path = document.querySelector('.loading path');

state = 0;

window.__loadinghandle = cycle(function(dt) {
  state += dt / 500;
  return path.setAttribute('d', calc(state));
});

setTimeout((function() {
  var svg, timeout;
  if (window.__loadinghandle == null) {
    return;
  }
  svg = document.querySelector('.loading .svg');
  svg.remove();
  timeout = document.querySelector('.loading .timeout');
  return timeout.style.display = 'block';
}), 10000);
