// Generated by CoffeeScript 1.8.0
var Checkbox, Checkboxes, Intro, NamesList, component, data, dom, _ref;

_ref = require('../lib/deku.min'), component = _ref.component, dom = _ref.dom;

data = require('./data');

Checkbox = component({
  render: function(props) {
    return dom('label', [
      dom('input', {
        type: 'checkbox',
        name: props.name,
        value: props.value
      }), props.text, dom('br')
    ]);
  }
});

Checkboxes = component({
  render: function(props) {
    var contents;
    contents = [dom('legend', props.text)];
    contents = contents.concat(props.checkboxes.map(function(p) {
      return Checkbox(p);
    }));
    return dom('fieldset', contents);
  }
});

NamesList = component({
  render: function() {
    var content, d, i, _i, _len, _ref1;
    content = [dom('legend', 'Names')];
    _ref1 = data.names;
    for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
      d = _ref1[i];
      content.push(dom('label', [
        "" + (i + 1) + ". ", dom('input', {
          type: 'text',
          name: "name-" + i,
          value: d
        })
      ]));
      content.push(dom('br'));
    }
    return dom('fieldset', content);
  }
});

Intro = component({
  render: function() {
    return dom('div', {
      "class": 'container'
    }, [
      dom('h1', "Tom and Havi's Wedding"), dom('p', "This is an invite for Mr MacGoo and Partner"), dom('p', "Please RSVP before 20th June 2015"), dom('form', [
        NamesList(), Checkboxes({
          text: 'Options',
          checkboxes: [
            {
              name: 'option',
              value: 1,
              text: 'Thingy'
            }, {
              name: 'option',
              value: 2,
              text: 'Dogs'
            }
          ]
        })
      ])
    ]);
  }
});

module.exports = component({
  render: function(props, state) {
    return dom('div', [Intro()]);
  }
});
