// Generated by CoffeeScript 1.8.0
var bind;

bind = function() {
  return {
    series: function(tasks, callback) {
      var next, result;
      tasks = tasks.slice(0);
      next = function(cb) {
        var task;
        if (tasks.length === 0) {
          return cb();
        }
        task = tasks.shift();
        return task(function() {
          return next(cb);
        });
      };
      result = function(cb) {
        return next(cb);
      };
      if (callback != null) {
        result(callback);
      }
      return result;
    },
    parallel: function(tasks, callback) {
      var count, result;
      count = tasks.length;
      result = function(cb) {
        var task, _i, _len, _results;
        if (count === 0) {
          return cb();
        }
        _results = [];
        for (_i = 0, _len = tasks.length; _i < _len; _i++) {
          task = tasks[_i];
          _results.push(task(function() {
            count--;
            if (count === 0) {
              return cb();
            }
          }));
        }
        return _results;
      };
      if (callback != null) {
        result(callback);
      }
      return result;
    },
    delay: function(callback) {
      return setTimeout(callback, 1);
    }
  };
};

if (typeof define !== "undefined" && define !== null) {
  define([], bind);
} else if (typeof module !== "undefined" && module !== null) {
  module.exports = bind();
} else {
  window.async = bind();
}
