// Generated by CoffeeScript 1.9.1
var Icon, component, dom, inject, ref, svg;

ref = require('odojs'), component = ref.component, dom = ref.dom, svg = ref.svg;

inject = require('injectinto');

require('svg4everybody');

Icon = component({
  render: function(state, params) {
    return dom('span', [
      svg('svg', {
        attributes: {
          role: 'img',
          "class": 'icon'
        }
      }, [
        svg('use', {
          'xlink:href': "/dist/weding-1.0.0.min.svg#" + params.i
        })
      ])
    ]);
  }
});

inject.bind('icon', Icon);

module.exports = Icon;
